# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


# for Firebase App Distributions -----
default_platform(:android)
platform :android do

  before_all do
#    - chmod +x gradlew <- for permission issue -> run in terminal

    ENV["FIREBASE_LOGIN_CREDENTIALS"] = "/Users/differenz70/Desktop/bhavin/serviceJsonKey/new_new_firebase_credentials.json"
    ENV["FIREBASE_APP_ID"] = "1:217528119112:android:5176557d338e0fa7e2cd7d"
    ENV["FLAVOR_NAME"] = ""

    ENV["RELEASE_NOTES_FILE"] = "/Users/differenz70/Desktop/bhavin/app/FirebaseAppDistributionConfig/release_notes.txt"
    ENV["GROUPS_FILE"] = "/Users/differenz70/Desktop/bhavin/app/FirebaseAppDistributionConfig/groups.txt"
  end

    desc "Lane for distributing Release app using Firebase App Distributions"
    lane :distributeReleaseBuild do
#         gradle(task: "clean assembleRelease")
#         gradle(task: "clean")
        gradle(task: "clean assemble", flavor: ENV["FLAVOR_NAME"], build_type: "Release")

        # find apk path
#         output_path = "./app/build/outputs/apk/"+ ENV["FLAVOR_NAME"]+"/release/"
#         output_path = "./app/build/outputs/apk/release/"
#         output_json_path = output_path + "output-metadata.json"
#         build_output = load_json(json_path: output_json_path)
#         elements = build_output["elements"][0]
#         apk_path = output_path + elements["outputFile"]
        apk_path = "/Users/differenz70/Desktop/bhavin/app/build/outputs/apk/release/app-release.apk"

        firebase_app_distribution(
            android_artifact_path: apk_path,
            app: ENV['FIREBASE_APP_ID'],
            service_credentials_file: ENV["FIREBASE_LOGIN_CREDENTIALS"],
            release_notes_file: ENV['RELEASE_NOTES_FILE'],
            groups_file: ENV['GROUPS_FILE'],
            android_artifact_type: "APK",
            debug: true,
        )
    end


    desc "After successful execution of all task, this block is called"
    lane :uploadToGit do
      git_add(path: "*")
      git_commit(
        path: "*",
#         path: "https://github.com/bhavien/bhavin.git",
#         message: "#" + UPDATED_VERSION_CODE + " released"
        message: "Helloooooooooooo"
      )

#       push_to_git_remote(
# #         local_branch: buildConfigs.key(options[:buildConfig]),
#         local_branch: "master",
#         remote: "origin",
# #         remote_branch: buildConfigs.key(options[:buildConfig]),
#         remote_branch: "master",
#         force: true,
#         tags: true,
#       )

      push_to_git_remote(
        remote: "origin",         # optional, default: "origin"
        local_branch: "master",  # optional, aliased by "branch", default is set to current branch
        remote_branch: "master", # optional, default is set to local_branch
      )

    end

end


